#!/usr/bin/env python3
"""Fail-closed structural validation for generated clean-room rhythm material."""

from __future__ import annotations

import hashlib
import csv
import json
import math
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
SPEC = ROOT / "dsp" / "spec"
RHYTHM_PATH = SPEC / "cleanroom_rhythm_patterns.json"
KIT_PATH = SPEC / "cleanroom_kit_profiles.json"
GENERATOR = SPEC / "build_cleanroom_rhythm.py"
GENERATED_HEADER = ROOT / "shared" / "dsp" / "include" / "webrc" / "dsp" / "cleanroom_rhythm_data.hpp"
GENERATED_CPP = ROOT / "shared" / "dsp" / "src" / "cleanroom_rhythm_data.cpp"
SOURCE_RHYTHM = SPEC / "source" / "rhythm_patterns_240.csv"
SOURCE_KITS = SPEC / "source" / "kits_16_algorithm_matrix.csv"
ALLOWED = {
    "kick", "snare", "closed_hat", "open_hat", "ride", "tom_low", "tom_high",
    "clap", "rim", "conga_low", "conga_high", "shaker", "brush_sweep",
}
SECTIONS = ("intro", "fill", "ending")


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(f"FAIL: {message}")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def event_key(events: list[dict[str, Any]]) -> str:
    return json.dumps(events, sort_keys=True, separators=(",", ":"))


def fingerprints(pattern: dict[str, Any]) -> dict[str, str]:
    events = pattern["variations"]["A"]
    meter = pattern["meter"]
    values = {
        "rawSequenceSha256": {"meter": meter, "events": [[e["tick"], e["instrument"]] for e in events]},
        "velocitySha256": {"meter": meter, "events": [[e["tick"], e["instrument"], e["velocity"]] for e in events]},
        "timingSha256": {"meter": meter, "swing": pattern["swing"]["amount"],
                         "events": [[e["tick"], e["swingable"]] for e in events]},
    }
    return {
        key: hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")).hexdigest()
        for key, value in values.items()
    }


def check_events(events: Any, bar_ticks: int, label: str) -> None:
    require(isinstance(events, list) and events, f"{label}: event list is empty or not a list")
    previous: tuple[int, str] | None = None
    seen: set[tuple[int, str]] = set()
    for event in events:
        require(isinstance(event, dict), f"{label}: event must be an object")
        tick = event.get("tick")
        instrument = event.get("instrument")
        velocity = event.get("velocity")
        require(type(tick) is int and 0 <= tick < bar_ticks, f"{label}: tick out of bounds")
        require(instrument in ALLOWED, f"{label}: unknown instrument {instrument!r}")
        require(type(velocity) is int and 1 <= velocity <= 127, f"{label}: velocity outside 1..127")
        require(type(event.get("swingable")) is bool, f"{label}: swingable must be boolean")
        duration = event.get("durationTicks")
        require(type(duration) is int and duration >= 0, f"{label}: durationTicks must be a nonnegative integer")
        if instrument == "brush_sweep":
            require(0 < duration <= bar_ticks and duration % 240 == 0,
                    f"{label}: brush sweep duration must fit and align to the phrase grid")
        else:
            require(duration == 0, f"{label}: one-shot event must have zero duration")
        key = (tick, instrument)
        require(previous is None or key > previous, f"{label}: events are not strictly sorted")
        require(key not in seen, f"{label}: duplicate tick/instrument")
        previous = key
        seen.add(key)


def main() -> None:
    rhythm = json.loads(RHYTHM_PATH.read_text(encoding="utf-8"))
    kits = json.loads(KIT_PATH.read_text(encoding="utf-8"))
    generated_header = GENERATED_HEADER.read_text(encoding="utf-8")
    generated_cpp = GENERATED_CPP.read_text(encoding="utf-8")
    generator_hash = sha256(GENERATOR)
    require(rhythm.get("schemaVersion") == "1.0.0", "unsupported rhythm schema")
    require(rhythm.get("generatorSha256") == generator_hash and
            kits.get("generatorSha256") == generator_hash,
            "clean-room metadata must be generated by the current hashed script")
    require(rhythm.get("count") == 240 and len(rhythm.get("patterns", [])) == 240,
            "rhythm pattern count must be exactly 240")
    require(rhythm.get("sourceCsvSha256") == sha256(SOURCE_RHYTHM), "rhythm source hash mismatch")
    require(kits.get("sourceCsvSha256") == sha256(SOURCE_KITS), "kit source hash mismatch")
    with SOURCE_RHYTHM.open(newline="", encoding="utf-8-sig") as stream:
        source_patterns = list(csv.DictReader(stream))
    with SOURCE_KITS.open(newline="", encoding="utf-8-sig") as stream:
        source_kits = list(csv.DictReader(stream))
    require(len(source_patterns) == 240 and len(source_kits) == 16,
            "source CSV row counts must independently equal 240 rhythms and 16 kits")
    rhythm_hash = sha256(RHYTHM_PATH)
    kit_hash = sha256(KIT_PATH)
    require(f"Generated from cleanroom_rhythm_patterns.json SHA256 {rhythm_hash}" in generated_cpp,
            "compiled rhythm table does not fingerprint the current pattern JSON")
    require(f"Generated from cleanroom_kit_profiles.json SHA256 {kit_hash}" in generated_cpp,
            "compiled kit table does not fingerprint the current kit JSON")
    require("cleanRoomRhythmPatternCount" in generated_header and
            "cleanRoomRhythmPattern" in generated_header and
            "cleanRoomRhythmPatternsSha256" in generated_header and
            "cleanRoomKitProfilesSha256" in generated_header,
            "generated public pattern/hash API is incomplete")
    require("cleanRoomKitCount() noexcept" in generated_cpp and
            "cleanRoomKitProfile(std::uint32_t index) noexcept" in generated_cpp,
            "generated C++ kit accessor is incomplete")
    require(rhythm.get("factoryMidiImported") is False and rhythm.get("factoryAudioImported") is False,
            "factory content import flags must remain false")
    require(rhythm.get("implementationStatus") ==
            "native_reference_renderer_implemented_browser_integration_pending",
            "rhythm runtime status must distinguish the Native reference from Browser integration")
    ids: set[str] = set()
    pattern_signatures: set[str] = set()
    main_hashes = {"rawSequenceSha256": set(), "velocitySha256": set(), "timingSha256": set()}
    classification_counts = {"preset": 0, "guide": 0, "user_slot_metadata": 0}
    for expected_slot, pattern in enumerate(rhythm["patterns"], 1):
        source = source_patterns[expected_slot - 1]
        slot = pattern.get("sourceSlot")
        require(slot == expected_slot, f"pattern order/index mismatch at slot {expected_slot}")
        require(pattern.get("id") == f"CR-RHY-{expected_slot:03d}", "unstable rhythm id")
        require(source.get("global_index") == str(expected_slot) and
                pattern.get("sourceGenreLabel") == source.get("genre", "").strip() and
                pattern.get("sourcePatternLabel") == source.get("pattern", "").strip() and
                f"{pattern.get('meter', {}).get('numerator')}/{pattern.get('meter', {}).get('denominator')}" == source.get("beat", "").strip(),
                f"{pattern['id']}: source metadata or meter differs from its CSV row")
        require(pattern["id"] not in ids, "duplicate rhythm id")
        ids.add(pattern["id"])
        classification_counts[pattern["classification"]] += 1
        meter = pattern.get("meter", {})
        numerator, denominator = meter.get("numerator"), meter.get("denominator")
        require(type(numerator) is int and numerator > 0 and type(denominator) is int and denominator > 0,
                f"{pattern['id']}: malformed meter")
        require(denominator in {4, 8}, f"{pattern['id']}: unsupported source meter denominator")
        require(pattern.get("ticksPerQuarter") == 960, f"{pattern['id']}: PPQ mismatch")
        require(pattern.get("barTicks") == numerator * 4 * 960 // denominator,
                f"{pattern['id']}: bar duration does not match meter")
        require(pattern.get("barsPerSection") == 1, f"{pattern['id']}: phrase size mismatch")
        variations = pattern.get("variations", {})
        require(set(variations) == {"A", "B", "C", "D"}, f"{pattern['id']}: variations A-D required")
        variant_keys: set[str] = set()
        for name in "ABCD":
            events = variations[name]
            check_events(events, pattern["barTicks"], f"{pattern['id']} variation {name}")
            require(all(event["tick"] % 240 == 0 for event in events),
                    f"{pattern['id']} variation {name}: event is off the authored sixteenth grid")
            signature = event_key(events)
            require(signature not in variant_keys, f"{pattern['id']}: duplicate variation {name}")
            variant_keys.add(signature)
        section_keys = set(variant_keys)
        for section in SECTIONS:
            events = pattern.get(section)
            check_events(events, pattern["barTicks"], f"{pattern['id']} {section}")
            require(all(event["tick"] % 240 == 0 for event in events),
                    f"{pattern['id']} {section}: event is off the authored sixteenth grid")
            signature = event_key(events)
            require(signature not in section_keys, f"{pattern['id']}: {section} is not a distinct arrangement")
            section_keys.add(signature)
        calculated = fingerprints(pattern)
        require(pattern.get("mainFingerprints") == calculated,
                f"{pattern['id']}: stored main fingerprints do not match event data")
        for key, value in calculated.items():
            main_hashes[key].add(value)
        swing = pattern.get("swing", {})
        amount = swing.get("amount")
        require(isinstance(amount, (int, float)) and 0 <= amount <= 1,
                f"{pattern['id']}: swing amount outside 0..1")
        require(swing.get("appliesOnlyToMarkedOffbeats") is True,
                f"{pattern['id']}: swing must be opt-in per event")
        prov = pattern.get("provenance", {})
        require(prov.get("kind") == "clean_room_rules" and prov.get("factoryMidiImported") is False and
                prov.get("factoryAudioImported") is False, f"{pattern['id']}: provenance mismatch")
        # Use all four variations so that two source slots cannot be accidental clones.
        signature = "|".join(event_key(variations[name]) for name in "ABCD")
        require(signature not in pattern_signatures, f"duplicate generated rhythm content at {pattern['id']}")
        pattern_signatures.add(signature)
    require(classification_counts == {"preset": 206, "guide": 33, "user_slot_metadata": 1},
            f"classification counts wrong: {classification_counts}")
    expected_fingerprint_counts = {
        "rawSequence": len(main_hashes["rawSequenceSha256"]),
        "velocity": len(main_hashes["velocitySha256"]),
        "timing": len(main_hashes["timingSha256"]),
    }
    require(rhythm.get("mainFingerprintUniqueCounts") == expected_fingerprint_counts,
            "main fingerprint summary disagrees with the actual event data")

    require(kits.get("count") == 16 and len(kits.get("profiles", [])) == 16,
            "kit count must be exactly 16")
    require(kits.get("sourceCsvSha256") == sha256(SOURCE_KITS), "kit source hash mismatch")
    require(kits.get("factoryAudioImported") is False and kits.get("factoryMidiImported") is False,
            "kit factory import flags must remain false")
    require(kits.get("implementationStatus") ==
            "native_procedural_reference_implemented_browser_integration_pending",
            "kit runtime status must distinguish Native reference from Browser integration")
    names: set[str] = set()
    kit_fingerprints: set[str] = set()
    for index, kit in enumerate(kits["profiles"], 1):
        source = source_kits[index - 1]
        require(kit.get("index") == index and kit.get("id") == f"CR-KIT-{index:02d}",
                f"unstable kit identity at {index}")
        require(source.get("index") == str(index) and
                kit.get("displayName") == source.get("official_kit_name", "").strip() and
                kit.get("designIntentLabel") == source.get("target_timbre", "").strip(),
                f"CR-KIT-{index:02d}: kit labels differ from the official metadata row")
        require(kit.get("displayName") not in names, "duplicate kit name")
        names.add(kit["displayName"])
        require(kit.get("nativeReferencePlaybackImplemented") is True and
                kit.get("browserPlaybackImplemented") is False and
                kit.get("audioQualityGatePassed") is False,
                "kit metadata must keep Native implementation, Browser integration, and Gate status distinct")
        require(kit.get("factorySamplesPresent") is False and kit.get("factoryMidiPresent") is False,
                f"{kit['id']}: forbidden factory asset flag")
        voice = kit.get("voiceParameters", {})
        require(set(voice) == {"kick", "snare", "closedHat", "openHat", "modal", "brushSweep"},
                f"{kit['id']}: missing procedural voice parameters")
        for section in voice.values():
            for key, value in section.items():
                require(isinstance(value, (int, float)) and math.isfinite(value),
                        f"{kit['id']}: nonnumeric profile field {key}")
        kit_fingerprints.add(json.dumps(voice, sort_keys=True, separators=(",", ":")))
    require(len(names) == 16 and len(kit_fingerprints) == 16, "kit profiles must be 16 distinct parameter sets")
    print("PASS: 240 clean-room patterns, four distinct variations each, unique slot content, valid meter/swing events")
    print("PASS: 16 distinct procedural profiles; Native reference only; Browser integration and quality gate pending")


if __name__ == "__main__":
    main()
